name: smart_parking_mobile
description: AI-Based Smart Parking Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Network
  dio: ^5.4.0
  socket_io_client: ^2.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.9
  
  # Utilities
  intl: ^0.18.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
